#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Develovers » Gemilangkinasih࿐
# Email      » gemilangkinasih@gmail.com
# telegram   » https://t.me/gemilangkinasih
# whatsapp   » wa.me/+628984880039
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Gemilangkinasih࿐

BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White
UWhite='\033[4;37m'       # White
BIYellow='\033[1;93m'     # Yellow
BGWHITE='\E[40;1;37m'     # Bgwhite

RED="\033[31m"
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
YELL='\033[0;33m'

# Getting
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
IP=$(cat /etc/xray/ipvps)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)

clear
read -p "Username : " Login
read -p "Password : " Pass
read -p "Limit Ip : " iplimit
read -p "Exxpired : " masaaktif

# limitip
if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/ssh/ip
echo -e "$iplimit" > /etc/kyt/limit/ssh/ip/$Login
else
echo > /dev/null
fi
clear

tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
expi="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`

DATADB=$(cat /etc/ssh/.ssh.db | grep "^###" | grep -w "${Login}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${Login}\b/d" /etc/ssh/.ssh.db
fi
echo "### ${Login} ${Pass} ${iplimit} ${expe}" >>/etc/ssh/.ssh.db

clear
cat > /var/www/html/ssh-$Login.txt <<-END
-----------------------------------
Format SSH OpenVPN Account
-----------------------------------
Username    : $Login
Password    : $Pass
Expired on  : $expe
Limit IP    : $iplimit User
-----------------------------------
IP Server   : $IP
Hostname    : $domain
OpenSSH     : 443, 80, 22
Dropbear    : 443, 109
SSH UDP     : 1-65535
SSH WS      : 80, 8080, 8081-9999
SSH SSL WS  : 443
SSL/TLS     : 400-900
OVPN WS SSL : 443
OVPN SSL    : 443
OVPN TCP    : 1194
OVPN UDP    : 2200
BadVPN UDP  : 7100, 7300, 7300
-----------------------------------
GET / HTTP/1.1[crlf]Host: $domain[host_port][crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]
-----------------------------------
https://$domain:81/ssh-$Login.txt
-----------------------------------
END

CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
☉────────────────────────☉
🧿Create SSH Account Success🧿
☉────────────────────────☉
<code>ISP          :</code> <code>$ISP</code>
<code>CITY         :</code> <code>$CITY</code>
☉────────────────────────☉
<code>Hostname     :</code> <code>$domain</code>
<code>Username     :</code> <code>$Login</code>
<code>Password     :</code> <code>$Pass</code>
<code>Limit IP     :</code> <code>$iplimit User</code>
<code>IP Server    :</code> <code>$IP</code>
☉────────────────────────☉
🧿<code>Expired $expe</code>🧿
☉────────────────────────☉
<code>OpenSSH      :</code> <code>22</code>
<code>Dropbear     :</code> <code>443, 109, 143</code>
<code>SSL/TLS      :</code> <code>400-900</code>
<code>SSH TLS      :</code> <code>443</code>
<code>SSH nTLS     :</code> <code>80, 8080, 8081-9999</code>
<code>BadVPN       :</code> <code>7100,7200,7300</code>
<code>OVPN TLS     :</code> <code>443</code>
<code>OVPN nTLS    :</code> <code>80, 8080, 8880</code>
☉────────────────────────☉
<code>TLS</code> <code>$domain:443@$Login:$Pass</code>

<code>nTLS</code> <code>$domain:80@$Login:$Pass</code>

<code>UDP</code> <code>$domain:1-65535@$Login:$Pass</code>
☉────────────────────────☉
🧿<code>GET / HTTP/1.1[crlf]Host: $domain[host_port][crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]</code>🧿
☉────────────────────────☉
🧿<code>https://$domain:81/ssh-$Login.txt</code>🧿
☉────────────────────────☉"

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
